### ISSUE TITLE
Publish schematics

### ISSUE THREAD

**Issue by namero999** [PricelessToolkit/Droplet#10]
Hello, I'm impressed by this project, it also addresses a lot of the questions I have around custom PCB design (such as integrating a custom ESP32 module). I think the schematics would be a terrific learning material. Is there any chance that you could publish them as well?

**Comment by PricelessToolkit** [comment]
schematic is made with the idea that it remains private. it's not for public sensitive eyes, I did a disgusting job :).  Nothing complicated in circuit design, search on the Internet for how to control a motor using a MOSFET and that’s it.
